### ISSUE TITLE
Missing Bounding Box

### ISSUE THREAD

**Issue by cniessner** [tuwien-geoweb-2015/g03_project#2]
@ahocevar 
Datenspeicher wurde hinzugefügt, Layer publiziert. Dabei kam es allerdings zu einem Problem, da die Bounding Boxen nicht automatisch definiert wurden und der Befehl "Aus Daten berechnen" nicht funkioniert.

![leere bounding box](https://cloud.githubusercontent.com/assets/15378018/12236965/a49cf48a-b87c-11e5-855c-7506263c9d48.PNG)

Folgende Fehlermeldung tritt nach dem Ausführen des Befehls auf:

![error](https://cloud.githubusercontent.com/assets/15378018/12236937/8a3fe78c-b87c-11e5-8c7a-ca58f1096071.PNG)

Wir haben zwar versucht die Bounding Boxen manuell festzulegen, dabei kam es jedoch zu einer weiteren Fehlermeldung:

![missing bounding box](https://cloud.githubusercontent.com/assets/15378018/12236901/69670af4-b87c-11e5-9e76-3ba6e730d4cc.PNG)

Offensichtlich haben wir entweder einen Fehler beim Upload eingebaut, oder in der Datenaufbereitung. Wie können wir das Problem lösen?

Liebe Grüße,
g03

**Comment by ahocevar** [comment]
Ich denke, ihr müsst nur wieder einmal Schema und Passwort aus der Datenspeicher-Konfiguration löschen.

**Comment by cniessner** [comment]
Super, hat funktioniert

**Comment by cniessner** [comment]
Wir waren soeben dabei die SQL View zu erstellen, der Select Befehl hat in Spatialite GUI problemlos funktioniert und es wurde uns das richtige Ergebnis ausgegeben.

Im Geoserver kommt es allerdings zu einer Fehlermeldung:

![sql view](https://cloud.githubusercontent.com/assets/15378018/12238421/37b6084a-b884-11e5-97d6-a810906be13d.PNG)

Die Attribute werden noch nicht vorgeschlagen, werden diese erst angezeigt, wenn der SQL Befehl fehlerfrei eingegeben wurde?
