### ISSUE TITLE
Kommentar Server-Adresse

### ISSUE THREAD

**Issue by cniessner** [tuwien-geoweb-2015/g03_project#6]
@ahocevar 
ich war soeben dabei die Kommentarfunktion einzurichten, dabei bin ich auf folgende Frage gestoßen:
Welche Adresse soll ich im Feld "featureType: 'comments', featureNS:" eintragen?

![server comments](https://cloud.githubusercontent.com/assets/15378018/12279306/b85726ca-b986-11e5-9cdf-66ae17b66170.PNG)

Wo werden die Kommentare genau gespeichert? In der comments - DB?

Liebe Grüße,
g03

**Comment by ahocevar** [comment]
`featureNS` ist die URL, die ihr in der GeoServer-Konfiguration für euren Workspace/Namensraum angegeben habt.

Die Kommentare werden in der Tabelle gespeichert, die ihr als `featureType` angegeben habt. Bei euch also offenbar 'comments'. Falls es die noch nicht gibt, müsst ihr sie in eurer Datenbank anlegen und in GeoServer daraus einen Layer erzeugen. Das ist der gleiche Vorgang wie mit der Feedback-Tabelle in Block 4.
